version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - govet
    - ineffassign
    - mirror
    - perfsprint
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - wastedassign
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/warpstreamlabs/bento/internal/batch.Error).Failed
        - (*github.com/warpstreamlabs/bento/public/service.BatchError).Failed
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - ifElseChain
        - ptrToRefParam
        - importShadow
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
        - deepequalerrors
        - shadow
      enable-all: true
    revive:
      enable-all-rules: false
      rules:
        - name: superfluous-else
    testifylint:
      disable-all: true
      enable:
        - nil-compare
        - compares
        - error-is-as
        - bool-compare
        - empty
        - len
        - expected-actual
        - error-nil
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - perfsprint
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
