version: 2
builds:
  - id: bento
    main: cmd/bento/main.go
    binary: bento
    goos: [ windows, darwin, linux, freebsd, openbsd ]
    goarch: [ amd64, arm, arm64 ]
    goarm: [ 6, 7 ]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X github.com/warpstreamlabs/bento/internal/cli.Version={{.Version}}
      -X github.com/warpstreamlabs/bento/internal/cli.DateBuilt={{.Date}}
      -X main.Version={{.Version}}
      -X main.DateBuilt={{.Date}}
  - id: bento-lambda
    main: cmd/serverless/bento-lambda/main.go
    binary: bento-lambda
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64 ]
  - id: bento-lambda-al2
    main: cmd/serverless/bento-lambda/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64, arm64 ]
archives:
  - id: bento
    builds: [ bento ]
    format: tar.gz
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE
  - id: bento-lambda
    builds: [ bento-lambda ]
    format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: bento-lambda-al2
    builds: [ bento-lambda-al2 ]
    format: zip
    name_template: "bento-lambda-al2_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dist: target/dist
release:
  github:
    owner: warpstreamlabs
    name: bento
  prerelease: auto
  disable: false
