input: 
  stdin: {}

pipeline:
  processors:
    - workflow:
        order: [ [ A ], [ B, C ], [ E ], [ D, F ] ]

        #       /--> B -------------|--> D
        #      /                   /
        # A --|          /--> E --|
        #      \--> C --|          \
        #                \----------|--> F

        branches:
          A:
            processors:
              - sleep:
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE A FINISHED

          B:
            processors:
              - sleep: 
                  duration: "15s"
              - log:
                  level: INFO
                  message: STAGE B FINISHED

          C:
            processors:
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE C FINISHED

          D:
            processors:
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE D FINISHED

          # Stage E won't exec until B has finished even though there is 
          # no direct dependency on B.
          E: 
            processors:
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE E FINISHED

          F:
            processors:
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE F FINISHED

output:
  stdout: {}