input: 
  file:
    paths: ["./cmd/bento/input_batch.json"]
    scanner:
      json_documents: {}

pipeline:
  processors:

    - unarchive:
        format: "json_array"
  
    - workflow:
        order: [ [ A ], [ B, C ], [ E ], [ D, F ] ]

        #       /--> B -------------|--> Ds
        #      /                   /
        # A --|          /--> E --|
        #      \--> C --|          \
        #                \----------|--> F

        branches:
          A:
            processors:
              - sleep:
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE A FINISHED

          B:
            processors:
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE B FINISHED

          C:
            processors:
              - sleep: 
                  duration: "1s"
              - branch:
                  request_map: |
                    root = if this.error == "error" {
                      this
                    } else {
                      deleted()
                    }
                  processors:
                    - log:
                        level: WARN
                        message: HELLO
                    - http:
                        url: asdfasdf
              - log:
                  level: INFO
                  message: STAGE C FINISHED

          D:
            processors:
              - mapping: |
                  root = this
                  root.test = "hello world"
              - sleep: 
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE D FINISHED
            result_map: |
                root = this

          E:
            processors:
              - sleep: 
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE E FINISHED

          F:
            processors:
              - sleep: 
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE F FINISHED

output:
  stdout: {}