input: 
  stdin: {}

pipeline:
  processors:
    - workflow_v2:

        #       /--> B -------------|--> D
        #      /                   /
        # A --|          /--> E --|
        #      \--> C --|          \
        #                \----------|--> F

        branches:
          A:
            processors:
              - mapping: |
                  root = this
                  root.branch_a = "hello, from branch A"
              - sleep:
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE A FINISHED
            result_map: |
                root = this

          B:
            dependency_list: ["A"]
            processors:
              - sleep: 
                  duration: "5s"
              - log:
                  level: INFO
                  message: STAGE B FINISHED

          C:
            dependency_list: ["A"]
            processors:
              - sleep: 
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE C FINISHED

          D:
            dependency_list: ["B", "E"]
            processors:
              - sleep: 
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE D FINISHED

          E:
            dependency_list: ["C"]
            processors:
              - sleep: 
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE E FINISHED

          F:
            dependency_list: ["C", "E"]
            processors:
              - mapping: |
                  root = this
                  root.branch_f = "hello, from branch F"
              - sleep: 
                  duration: "1s"
              - log:
                  level: INFO
                  message: STAGE F FINISHED
            result_map: |
                root = this


output:
  stdout: {}
