// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: spec.proto

package specpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNKNOWN    FieldType = 0
	FieldType_FIELD_TYPE_STRING     FieldType = 1
	FieldType_FIELD_TYPE_INT        FieldType = 2
	FieldType_FIELD_TYPE_FLOAT      FieldType = 3
	FieldType_FIELD_TYPE_BOOL       FieldType = 4
	FieldType_FIELD_TYPE_OBJECT     FieldType = 5
	FieldType_FIELD_TYPE_INPUT      FieldType = 10
	FieldType_FIELD_TYPE_BUFFER     FieldType = 11
	FieldType_FIELD_TYPE_CACHE      FieldType = 12
	FieldType_FIELD_TYPE_PROCESSOR  FieldType = 13
	FieldType_FIELD_TYPE_RATE_LIMIT FieldType = 14
	FieldType_FIELD_TYPE_OUTPUT     FieldType = 15
	FieldType_FIELD_TYPE_METRICS    FieldType = 16
	FieldType_FIELD_TYPE_TRACER     FieldType = 17
	FieldType_FIELD_TYPE_SCANNER    FieldType = 18
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0:  "FIELD_TYPE_UNKNOWN",
		1:  "FIELD_TYPE_STRING",
		2:  "FIELD_TYPE_INT",
		3:  "FIELD_TYPE_FLOAT",
		4:  "FIELD_TYPE_BOOL",
		5:  "FIELD_TYPE_OBJECT",
		10: "FIELD_TYPE_INPUT",
		11: "FIELD_TYPE_BUFFER",
		12: "FIELD_TYPE_CACHE",
		13: "FIELD_TYPE_PROCESSOR",
		14: "FIELD_TYPE_RATE_LIMIT",
		15: "FIELD_TYPE_OUTPUT",
		16: "FIELD_TYPE_METRICS",
		17: "FIELD_TYPE_TRACER",
		18: "FIELD_TYPE_SCANNER",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNKNOWN":    0,
		"FIELD_TYPE_STRING":     1,
		"FIELD_TYPE_INT":        2,
		"FIELD_TYPE_FLOAT":      3,
		"FIELD_TYPE_BOOL":       4,
		"FIELD_TYPE_OBJECT":     5,
		"FIELD_TYPE_INPUT":      10,
		"FIELD_TYPE_BUFFER":     11,
		"FIELD_TYPE_CACHE":      12,
		"FIELD_TYPE_PROCESSOR":  13,
		"FIELD_TYPE_RATE_LIMIT": 14,
		"FIELD_TYPE_OUTPUT":     15,
		"FIELD_TYPE_METRICS":    16,
		"FIELD_TYPE_TRACER":     17,
		"FIELD_TYPE_SCANNER":    18,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_spec_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{0}
}

type FieldKind int32

const (
	FieldKind_FIELD_KIND_UNKNOWN  FieldKind = 0
	FieldKind_FIELD_KIND_SCALAR   FieldKind = 1
	FieldKind_FIELD_KIND_ARRAY    FieldKind = 2
	FieldKind_FIELD_KIND_2D_ARRAY FieldKind = 3
	FieldKind_FIELD_KIND_MAP      FieldKind = 4
)

// Enum value maps for FieldKind.
var (
	FieldKind_name = map[int32]string{
		0: "FIELD_KIND_UNKNOWN",
		1: "FIELD_KIND_SCALAR",
		2: "FIELD_KIND_ARRAY",
		3: "FIELD_KIND_2D_ARRAY",
		4: "FIELD_KIND_MAP",
	}
	FieldKind_value = map[string]int32{
		"FIELD_KIND_UNKNOWN":  0,
		"FIELD_KIND_SCALAR":   1,
		"FIELD_KIND_ARRAY":    2,
		"FIELD_KIND_2D_ARRAY": 3,
		"FIELD_KIND_MAP":      4,
	}
)

func (x FieldKind) Enum() *FieldKind {
	p := new(FieldKind)
	*p = x
	return p
}

func (x FieldKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldKind) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_proto_enumTypes[1].Descriptor()
}

func (FieldKind) Type() protoreflect.EnumType {
	return &file_spec_proto_enumTypes[1]
}

func (x FieldKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldKind.Descriptor instead.
func (FieldKind) EnumDescriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{1}
}

type ComponentType int32

const (
	ComponentType_COMPONENT_TYPE_UNKNOWN    ComponentType = 0
	ComponentType_COMPONENT_TYPE_INPUT      ComponentType = 1
	ComponentType_COMPONENT_TYPE_BUFFER     ComponentType = 2
	ComponentType_COMPONENT_TYPE_CACHE      ComponentType = 3
	ComponentType_COMPONENT_TYPE_METRICS    ComponentType = 4
	ComponentType_COMPONENT_TYPE_OUTPUT     ComponentType = 5
	ComponentType_COMPONENT_TYPE_PROCESSOR  ComponentType = 6
	ComponentType_COMPONENT_TYPE_RATE_LIMIT ComponentType = 7
	ComponentType_COMPONENT_TYPE_TRACER     ComponentType = 8
	ComponentType_COMPONENT_TYPE_SCANNER    ComponentType = 9
)

// Enum value maps for ComponentType.
var (
	ComponentType_name = map[int32]string{
		0: "COMPONENT_TYPE_UNKNOWN",
		1: "COMPONENT_TYPE_INPUT",
		2: "COMPONENT_TYPE_BUFFER",
		3: "COMPONENT_TYPE_CACHE",
		4: "COMPONENT_TYPE_METRICS",
		5: "COMPONENT_TYPE_OUTPUT",
		6: "COMPONENT_TYPE_PROCESSOR",
		7: "COMPONENT_TYPE_RATE_LIMIT",
		8: "COMPONENT_TYPE_TRACER",
		9: "COMPONENT_TYPE_SCANNER",
	}
	ComponentType_value = map[string]int32{
		"COMPONENT_TYPE_UNKNOWN":    0,
		"COMPONENT_TYPE_INPUT":      1,
		"COMPONENT_TYPE_BUFFER":     2,
		"COMPONENT_TYPE_CACHE":      3,
		"COMPONENT_TYPE_METRICS":    4,
		"COMPONENT_TYPE_OUTPUT":     5,
		"COMPONENT_TYPE_PROCESSOR":  6,
		"COMPONENT_TYPE_RATE_LIMIT": 7,
		"COMPONENT_TYPE_TRACER":     8,
		"COMPONENT_TYPE_SCANNER":    9,
	}
)

func (x ComponentType) Enum() *ComponentType {
	p := new(ComponentType)
	*p = x
	return p
}

func (x ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_proto_enumTypes[2].Descriptor()
}

func (ComponentType) Type() protoreflect.EnumType {
	return &file_spec_proto_enumTypes[2]
}

func (x ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentType.Descriptor instead.
func (ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{2}
}

type ComponentStatus int32

const (
	ComponentStatus_COMPONENT_STATUS_UNKNOWN      ComponentStatus = 0
	ComponentStatus_COMPONENT_STATUS_STABLE       ComponentStatus = 1
	ComponentStatus_COMPONENT_STATUS_BETA         ComponentStatus = 2
	ComponentStatus_COMPONENT_STATUS_EXPERIMENTAL ComponentStatus = 3
	ComponentStatus_COMPONENT_STATUS_DEPRECATED   ComponentStatus = 4
)

// Enum value maps for ComponentStatus.
var (
	ComponentStatus_name = map[int32]string{
		0: "COMPONENT_STATUS_UNKNOWN",
		1: "COMPONENT_STATUS_STABLE",
		2: "COMPONENT_STATUS_BETA",
		3: "COMPONENT_STATUS_EXPERIMENTAL",
		4: "COMPONENT_STATUS_DEPRECATED",
	}
	ComponentStatus_value = map[string]int32{
		"COMPONENT_STATUS_UNKNOWN":      0,
		"COMPONENT_STATUS_STABLE":       1,
		"COMPONENT_STATUS_BETA":         2,
		"COMPONENT_STATUS_EXPERIMENTAL": 3,
		"COMPONENT_STATUS_DEPRECATED":   4,
	}
)

func (x ComponentStatus) Enum() *ComponentStatus {
	p := new(ComponentStatus)
	*p = x
	return p
}

func (x ComponentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_proto_enumTypes[3].Descriptor()
}

func (ComponentStatus) Type() protoreflect.EnumType {
	return &file_spec_proto_enumTypes[3]
}

func (x ComponentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentStatus.Descriptor instead.
func (ComponentStatus) EnumDescriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{3}
}

type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to FieldType:
	//
	//	*FieldValue_StringType
	//	*FieldValue_IntType
	//	*FieldValue_FloatType
	//	*FieldValue_BoolType
	//	*FieldValue_ObjectType
	FieldType     isFieldValue_FieldType `protobuf_oneof:"field_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{0}
}

func (x *FieldValue) GetFieldType() isFieldValue_FieldType {
	if x != nil {
		return x.FieldType
	}
	return nil
}

func (x *FieldValue) GetStringType() string {
	if x != nil {
		if x, ok := x.FieldType.(*FieldValue_StringType); ok {
			return x.StringType
		}
	}
	return ""
}

func (x *FieldValue) GetIntType() int32 {
	if x != nil {
		if x, ok := x.FieldType.(*FieldValue_IntType); ok {
			return x.IntType
		}
	}
	return 0
}

func (x *FieldValue) GetFloatType() float32 {
	if x != nil {
		if x, ok := x.FieldType.(*FieldValue_FloatType); ok {
			return x.FloatType
		}
	}
	return 0
}

func (x *FieldValue) GetBoolType() bool {
	if x != nil {
		if x, ok := x.FieldType.(*FieldValue_BoolType); ok {
			return x.BoolType
		}
	}
	return false
}

func (x *FieldValue) GetObjectType() *structpb.Value {
	if x != nil {
		if x, ok := x.FieldType.(*FieldValue_ObjectType); ok {
			return x.ObjectType
		}
	}
	return nil
}

type isFieldValue_FieldType interface {
	isFieldValue_FieldType()
}

type FieldValue_StringType struct {
	StringType string `protobuf:"bytes,1,opt,name=string_type,json=stringType,proto3,oneof"`
}

type FieldValue_IntType struct {
	IntType int32 `protobuf:"varint,2,opt,name=int_type,json=intType,proto3,oneof"`
}

type FieldValue_FloatType struct {
	FloatType float32 `protobuf:"fixed32,3,opt,name=float_type,json=floatType,proto3,oneof"`
}

type FieldValue_BoolType struct {
	BoolType bool `protobuf:"varint,4,opt,name=bool_type,json=boolType,proto3,oneof"`
}

type FieldValue_ObjectType struct {
	ObjectType *structpb.Value `protobuf:"bytes,5,opt,name=object_type,json=objectType,proto3,oneof"`
}

func (*FieldValue_StringType) isFieldValue_FieldType() {}

func (*FieldValue_IntType) isFieldValue_FieldType() {}

func (*FieldValue_FloatType) isFieldValue_FieldType() {}

func (*FieldValue_BoolType) isFieldValue_FieldType() {}

func (*FieldValue_ObjectType) isFieldValue_FieldType() {}

type FieldSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FieldType     FieldType              `protobuf:"varint,2,opt,name=field_type,json=fieldType,proto3,enum=specpb.FieldType" json:"field_type,omitempty"`
	FieldKind     FieldKind              `protobuf:"varint,3,opt,name=field_kind,json=fieldKind,proto3,enum=specpb.FieldKind" json:"field_kind,omitempty"`
	IsOptional    bool                   `protobuf:"varint,4,opt,name=is_optional,json=isOptional,proto3" json:"is_optional,omitempty"`
	IsSecret      bool                   `protobuf:"varint,5,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"`
	DefaultValue  *FieldValue            `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Interpolated  bool                   `protobuf:"varint,7,opt,name=interpolated,proto3" json:"interpolated,omitempty"`
	Bloblang      bool                   `protobuf:"varint,8,opt,name=bloblang,proto3" json:"bloblang,omitempty"`
	Options       []string               `protobuf:"bytes,9,rep,name=options,proto3" json:"options,omitempty"`
	Children      []*FieldSpec           `protobuf:"bytes,10,rep,name=children,proto3" json:"children,omitempty"`
	Linter        *string                `protobuf:"bytes,11,opt,name=linter,proto3,oneof" json:"linter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSpec) Reset() {
	*x = FieldSpec{}
	mi := &file_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSpec) ProtoMessage() {}

func (x *FieldSpec) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSpec.ProtoReflect.Descriptor instead.
func (*FieldSpec) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{1}
}

func (x *FieldSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldSpec) GetFieldType() FieldType {
	if x != nil {
		return x.FieldType
	}
	return FieldType_FIELD_TYPE_UNKNOWN
}

func (x *FieldSpec) GetFieldKind() FieldKind {
	if x != nil {
		return x.FieldKind
	}
	return FieldKind_FIELD_KIND_UNKNOWN
}

func (x *FieldSpec) GetIsOptional() bool {
	if x != nil {
		return x.IsOptional
	}
	return false
}

func (x *FieldSpec) GetIsSecret() bool {
	if x != nil {
		return x.IsSecret
	}
	return false
}

func (x *FieldSpec) GetDefaultValue() *FieldValue {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *FieldSpec) GetInterpolated() bool {
	if x != nil {
		return x.Interpolated
	}
	return false
}

func (x *FieldSpec) GetBloblang() bool {
	if x != nil {
		return x.Bloblang
	}
	return false
}

func (x *FieldSpec) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FieldSpec) GetChildren() []*FieldSpec {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *FieldSpec) GetLinter() string {
	if x != nil && x.Linter != nil {
		return *x.Linter
	}
	return ""
}

type ComponentSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ComponentType   ComponentType          `protobuf:"varint,2,opt,name=component_type,json=componentType,proto3,enum=specpb.ComponentType" json:"component_type,omitempty"`
	ComponentStatus ComponentStatus        `protobuf:"varint,3,opt,name=component_status,json=componentStatus,proto3,enum=specpb.ComponentStatus" json:"component_status,omitempty"`
	Config          *FieldSpec             `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComponentSpec) Reset() {
	*x = ComponentSpec{}
	mi := &file_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentSpec) ProtoMessage() {}

func (x *ComponentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentSpec.ProtoReflect.Descriptor instead.
func (*ComponentSpec) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentSpec) GetComponentType() ComponentType {
	if x != nil {
		return x.ComponentType
	}
	return ComponentType_COMPONENT_TYPE_UNKNOWN
}

func (x *ComponentSpec) GetComponentStatus() ComponentStatus {
	if x != nil {
		return x.ComponentStatus
	}
	return ComponentStatus_COMPONENT_STATUS_UNKNOWN
}

func (x *ComponentSpec) GetConfig() *FieldSpec {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_spec_proto protoreflect.FileDescriptor

const file_spec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"spec.proto\x12\x06specpb\x1a\x1cgoogle/protobuf/struct.proto\"\xd5\x01\n" +
	"\n" +
	"FieldValue\x12!\n" +
	"\vstring_type\x18\x01 \x01(\tH\x00R\n" +
	"stringType\x12\x1b\n" +
	"\bint_type\x18\x02 \x01(\x05H\x00R\aintType\x12\x1f\n" +
	"\n" +
	"float_type\x18\x03 \x01(\x02H\x00R\tfloatType\x12\x1d\n" +
	"\tbool_type\x18\x04 \x01(\bH\x00R\bboolType\x129\n" +
	"\vobject_type\x18\x05 \x01(\v2\x16.google.protobuf.ValueH\x00R\n" +
	"objectTypeB\f\n" +
	"\n" +
	"field_type\"\xc2\x03\n" +
	"\tFieldSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\n" +
	"field_type\x18\x02 \x01(\x0e2\x11.specpb.FieldTypeR\tfieldType\x120\n" +
	"\n" +
	"field_kind\x18\x03 \x01(\x0e2\x11.specpb.FieldKindR\tfieldKind\x12\x1f\n" +
	"\vis_optional\x18\x04 \x01(\bR\n" +
	"isOptional\x12\x1b\n" +
	"\tis_secret\x18\x05 \x01(\bR\bisSecret\x12<\n" +
	"\rdefault_value\x18\x06 \x01(\v2\x12.specpb.FieldValueH\x00R\fdefaultValue\x88\x01\x01\x12\"\n" +
	"\finterpolated\x18\a \x01(\bR\finterpolated\x12\x1a\n" +
	"\bbloblang\x18\b \x01(\bR\bbloblang\x12\x18\n" +
	"\aoptions\x18\t \x03(\tR\aoptions\x12-\n" +
	"\bchildren\x18\n" +
	" \x03(\v2\x11.specpb.FieldSpecR\bchildren\x12\x1b\n" +
	"\x06linter\x18\v \x01(\tH\x01R\x06linter\x88\x01\x01B\x10\n" +
	"\x0e_default_valueB\t\n" +
	"\a_linter\"\xd0\x01\n" +
	"\rComponentSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x0ecomponent_type\x18\x02 \x01(\x0e2\x15.specpb.ComponentTypeR\rcomponentType\x12B\n" +
	"\x10component_status\x18\x03 \x01(\x0e2\x17.specpb.ComponentStatusR\x0fcomponentStatus\x12)\n" +
	"\x06config\x18\x04 \x01(\v2\x11.specpb.FieldSpecR\x06config*\xe6\x02\n" +
	"\tFieldType\x12\x16\n" +
	"\x12FIELD_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11FIELD_TYPE_STRING\x10\x01\x12\x12\n" +
	"\x0eFIELD_TYPE_INT\x10\x02\x12\x14\n" +
	"\x10FIELD_TYPE_FLOAT\x10\x03\x12\x13\n" +
	"\x0fFIELD_TYPE_BOOL\x10\x04\x12\x15\n" +
	"\x11FIELD_TYPE_OBJECT\x10\x05\x12\x14\n" +
	"\x10FIELD_TYPE_INPUT\x10\n" +
	"\x12\x15\n" +
	"\x11FIELD_TYPE_BUFFER\x10\v\x12\x14\n" +
	"\x10FIELD_TYPE_CACHE\x10\f\x12\x18\n" +
	"\x14FIELD_TYPE_PROCESSOR\x10\r\x12\x19\n" +
	"\x15FIELD_TYPE_RATE_LIMIT\x10\x0e\x12\x15\n" +
	"\x11FIELD_TYPE_OUTPUT\x10\x0f\x12\x16\n" +
	"\x12FIELD_TYPE_METRICS\x10\x10\x12\x15\n" +
	"\x11FIELD_TYPE_TRACER\x10\x11\x12\x16\n" +
	"\x12FIELD_TYPE_SCANNER\x10\x12*}\n" +
	"\tFieldKind\x12\x16\n" +
	"\x12FIELD_KIND_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11FIELD_KIND_SCALAR\x10\x01\x12\x14\n" +
	"\x10FIELD_KIND_ARRAY\x10\x02\x12\x17\n" +
	"\x13FIELD_KIND_2D_ARRAY\x10\x03\x12\x12\n" +
	"\x0eFIELD_KIND_MAP\x10\x04*\xa5\x02\n" +
	"\rComponentType\x12\x1a\n" +
	"\x16COMPONENT_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14COMPONENT_TYPE_INPUT\x10\x01\x12\x19\n" +
	"\x15COMPONENT_TYPE_BUFFER\x10\x02\x12\x18\n" +
	"\x14COMPONENT_TYPE_CACHE\x10\x03\x12\x1a\n" +
	"\x16COMPONENT_TYPE_METRICS\x10\x04\x12\x19\n" +
	"\x15COMPONENT_TYPE_OUTPUT\x10\x05\x12\x1c\n" +
	"\x18COMPONENT_TYPE_PROCESSOR\x10\x06\x12\x1d\n" +
	"\x19COMPONENT_TYPE_RATE_LIMIT\x10\a\x12\x19\n" +
	"\x15COMPONENT_TYPE_TRACER\x10\b\x12\x1a\n" +
	"\x16COMPONENT_TYPE_SCANNER\x10\t*\xab\x01\n" +
	"\x0fComponentStatus\x12\x1c\n" +
	"\x18COMPONENT_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17COMPONENT_STATUS_STABLE\x10\x01\x12\x19\n" +
	"\x15COMPONENT_STATUS_BETA\x10\x02\x12!\n" +
	"\x1dCOMPONENT_STATUS_EXPERIMENTAL\x10\x03\x12\x1f\n" +
	"\x1bCOMPONENT_STATUS_DEPRECATED\x10\x04B6Z4github.com/warpstreamlabs/bento/internal/docs/specpbb\x06proto3"

var (
	file_spec_proto_rawDescOnce sync.Once
	file_spec_proto_rawDescData []byte
)

func file_spec_proto_rawDescGZIP() []byte {
	file_spec_proto_rawDescOnce.Do(func() {
		file_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_proto_rawDesc), len(file_spec_proto_rawDesc)))
	})
	return file_spec_proto_rawDescData
}

var file_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spec_proto_goTypes = []any{
	(FieldType)(0),         // 0: specpb.FieldType
	(FieldKind)(0),         // 1: specpb.FieldKind
	(ComponentType)(0),     // 2: specpb.ComponentType
	(ComponentStatus)(0),   // 3: specpb.ComponentStatus
	(*FieldValue)(nil),     // 4: specpb.FieldValue
	(*FieldSpec)(nil),      // 5: specpb.FieldSpec
	(*ComponentSpec)(nil),  // 6: specpb.ComponentSpec
	(*structpb.Value)(nil), // 7: google.protobuf.Value
}
var file_spec_proto_depIdxs = []int32{
	7, // 0: specpb.FieldValue.object_type:type_name -> google.protobuf.Value
	0, // 1: specpb.FieldSpec.field_type:type_name -> specpb.FieldType
	1, // 2: specpb.FieldSpec.field_kind:type_name -> specpb.FieldKind
	4, // 3: specpb.FieldSpec.default_value:type_name -> specpb.FieldValue
	5, // 4: specpb.FieldSpec.children:type_name -> specpb.FieldSpec
	2, // 5: specpb.ComponentSpec.component_type:type_name -> specpb.ComponentType
	3, // 6: specpb.ComponentSpec.component_status:type_name -> specpb.ComponentStatus
	5, // 7: specpb.ComponentSpec.config:type_name -> specpb.FieldSpec
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_spec_proto_init() }
func file_spec_proto_init() {
	if File_spec_proto != nil {
		return
	}
	file_spec_proto_msgTypes[0].OneofWrappers = []any{
		(*FieldValue_StringType)(nil),
		(*FieldValue_IntType)(nil),
		(*FieldValue_FloatType)(nil),
		(*FieldValue_BoolType)(nil),
		(*FieldValue_ObjectType)(nil),
	}
	file_spec_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_proto_rawDesc), len(file_spec_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_proto_goTypes,
		DependencyIndexes: file_spec_proto_depIdxs,
		EnumInfos:         file_spec_proto_enumTypes,
		MessageInfos:      file_spec_proto_msgTypes,
	}.Build()
	File_spec_proto = out.File
	file_spec_proto_goTypes = nil
	file_spec_proto_depIdxs = nil
}
