#!/usr/bin/env bash
#
# Installs Bento the quick way, for adventurers that want to spend more time
# grooming their cats.
#
# Requires curl, grep, cut, tar, uname, chmod, mv, rm.

[[ $- = *i* ]] && echo "Don't source this script!" && return 10

header() {
		cat 1>&2 <<EOF
Bento Installer

Website: https://github.com/warpstreamlabs/bento
Docs:  https://github.com/warpstreamlabs/bento
Repo: https://github.com/warpstreamlabs/bento

EOF
}

check_cmd() {
	command -v "$1" > /dev/null 2>&1
}

check_tools() {
	Tools=("curl" "grep" "cut" "tar" "uname" "chmod" "mv" "rm")

	for tool in ${Tools[*]}; do
		if ! check_cmd $tool; then
			echo "Aborted, missing $tool, sorry!"
			exit 6
		fi
	done
}

install_bento()
{
	trap 'echo -e "Aborted, error $? in command: $BASH_COMMAND"; trap ERR; exit 1' ERR

	# Process the command line
	if [[ "$#" -eq 2 ]]; then
		bento_tag="v$1"
		bento_version="$1"
		bento_install_path="$2"
	elif [[ "$#" -eq 1 ]]; then
		bento_tag="v$1"
		bento_version=$1
		bento_install_path="/usr/local/bin"
	elif [[ "$#" -eq 0 ]]; then
		bento_tag=$(curl -s https://api.github.com/repos/warpstreamlabs/bento/releases/latest | grep 'tag_name' | cut -d\" -f4)
		bento_version=$(echo ${bento_tag} | cut -c2-)
		bento_install_path="/usr/local/bin"
	else
		echo "Too many arguments."
		exit 1
	fi

	bento_os="unsupported"
	bento_arch="unknown"
	bento_arm=""

	header
	check_tools

	if [[ -n "$PREFIX" ]]; then
		bento_install_path="$PREFIX/bin"
	fi

	# Fall back to /usr/bin if necessary
	if [[ ! -d $bento_install_path ]]; then
		bento_install_path="/usr/bin"
	fi

	# Not every platform has or needs sudo (https://termux.com/linux.html)
	((EUID)) && sudo_cmd="sudo"

	#########################
	# Which OS and version? #
	#########################

	bento_bin="bento"
	bento_dl_ext=".tar.gz"

	# NOTE: `uname -m` is more accurate and universal than `arch`
	# See https://en.wikipedia.org/wiki/Uname
	unamem="$(uname -m)"
	if [[ $unamem == *aarch64* ]]; then
		bento_arch="arm64"
	elif [[ $unamem == *arm64* ]]; then
		bento_arch="arm64"
	elif [[ $unamem == *64* ]]; then
		bento_arch="amd64"
	elif [[ $unamem == *armv5* ]]; then
		bento_arch="arm"
		bento_arm="v5"
	elif [[ $unamem == *armv6l* ]]; then
		bento_arch="arm"
		bento_arm="v6"
	elif [[ $unamem == *armv7l* ]]; then
		bento_arch="arm"
		bento_arm="v7"
	else
		echo "Aborted, unsupported or unknown architecture: $unamem"
		return 2
	fi

	unameu="$(tr '[:lower:]' '[:upper:]' <<<$(uname))"
	if [[ $unameu == *DARWIN* ]]; then
		bento_os="darwin"
		version=${vers##*ProductVersion:}
	elif [[ $unameu == *LINUX* ]]; then
		bento_os="linux"
	elif [[ $unameu == *FREEBSD* ]]; then
		bento_os="freebsd"
	elif [[ $unameu == *OPENBSD* ]]; then
		bento_os="openbsd"
	elif [[ $unameu == *WIN* || $unameu == MSYS* ]]; then
		# Should catch cygwin
		sudo_cmd=""
		bento_os="windows"
		bento_bin=$bento_bin.exe
	else
		echo "Aborted, unsupported or unknown os: $uname"
		return 6
	fi

	########################
	# Download and extract #
	########################

	echo "Downloading Bento for ${bento_os}/${bento_arch}${bento_arm}..."
	bento_file="bento_${bento_os}_${bento_arch}${bento_arm}${bento_dl_ext}"

	bento_url="https://github.com/warpstreamlabs/bento/releases/download/${bento_tag}/bento_${bento_version}_${bento_os}_${bento_arch}${bento_arm}.tar.gz"

	dl="/tmp/$bento_file"
	rm -rf -- "$dl"

	curl -fsSL "$bento_url" -o "$dl"

	echo "Extracting..."
	case "$bento_file" in
		*.tar.gz) tar -xzf "$dl" -C "$PREFIX/tmp/" "$bento_bin" ;;
	esac
	chmod +x "$PREFIX/tmp/$bento_bin"

	echo "Putting bento in $bento_install_path (may require password)"
	if [ -n "$sudo_cmd" ] && [ -n "$(find "$bento_install_path" -prune -user "$(id -u)")" ]; then
		# Skip sudo if the current user is the owner of the Bento install path
		sudo_cmd=""
	fi
	$sudo_cmd mv "$PREFIX/tmp/$bento_bin" "$bento_install_path/$bento_bin"
	$sudo_cmd rm -- "$dl"

	# check installation
	$bento_install_path/$bento_bin -version
	if ! check_cmd bento; then
		echo "Do not forget to add $bento_install_path to your PATH!"
	fi

	echo "Successfully installed"
	trap ERR
	return 0
}

install_bento $@
