name: govulncheck
on:
  push:
    paths:
      - go.mod
      - go.sum
  pull_request:
    paths:
      - go.mod
      - go.sum
  schedule: 
    # Daily at 8:00 UTC
    - cron: '8 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest ./...