// Package all imports all component implementations that ship with the open
// source Bento repo. This is a convenient way of importing every single
// connector at the cost of a larger dependency tree for your application.
package all

import (
	// Import all public sub-categories.
	_ "github.com/warpstreamlabs/bento/v4/public/components/amqp09"
	_ "github.com/warpstreamlabs/bento/v4/public/components/amqp1"
	_ "github.com/warpstreamlabs/bento/v4/public/components/avro"
	_ "github.com/warpstreamlabs/bento/v4/public/components/aws"
	_ "github.com/warpstreamlabs/bento/v4/public/components/azure"
	_ "github.com/warpstreamlabs/bento/v4/public/components/beanstalkd"
	_ "github.com/warpstreamlabs/bento/v4/public/components/cassandra"
	_ "github.com/warpstreamlabs/bento/v4/public/components/changelog"
	_ "github.com/warpstreamlabs/bento/v4/public/components/cockroachdb"
	_ "github.com/warpstreamlabs/bento/v4/public/components/confluent"
	_ "github.com/warpstreamlabs/bento/v4/public/components/couchbase"
	_ "github.com/warpstreamlabs/bento/v4/public/components/crypto"
	_ "github.com/warpstreamlabs/bento/v4/public/components/dgraph"
	_ "github.com/warpstreamlabs/bento/v4/public/components/discord"
	_ "github.com/warpstreamlabs/bento/v4/public/components/elasticsearch"
	_ "github.com/warpstreamlabs/bento/v4/public/components/gcp"
	_ "github.com/warpstreamlabs/bento/v4/public/components/hdfs"
	_ "github.com/warpstreamlabs/bento/v4/public/components/influxdb"
	_ "github.com/warpstreamlabs/bento/v4/public/components/io"
	_ "github.com/warpstreamlabs/bento/v4/public/components/jaeger"
	_ "github.com/warpstreamlabs/bento/v4/public/components/javascript"
	_ "github.com/warpstreamlabs/bento/v4/public/components/kafka"
	_ "github.com/warpstreamlabs/bento/v4/public/components/maxmind"
	_ "github.com/warpstreamlabs/bento/v4/public/components/memcached"
	_ "github.com/warpstreamlabs/bento/v4/public/components/mongodb"
	_ "github.com/warpstreamlabs/bento/v4/public/components/mqtt"
	_ "github.com/warpstreamlabs/bento/v4/public/components/msgpack"
	_ "github.com/warpstreamlabs/bento/v4/public/components/nanomsg"
	_ "github.com/warpstreamlabs/bento/v4/public/components/nats"
	_ "github.com/warpstreamlabs/bento/v4/public/components/nsq"
	_ "github.com/warpstreamlabs/bento/v4/public/components/opensearch"
	_ "github.com/warpstreamlabs/bento/v4/public/components/otlp"
	_ "github.com/warpstreamlabs/bento/v4/public/components/prometheus"
	_ "github.com/warpstreamlabs/bento/v4/public/components/pulsar"
	_ "github.com/warpstreamlabs/bento/v4/public/components/pure"
	_ "github.com/warpstreamlabs/bento/v4/public/components/pure/extended"
	_ "github.com/warpstreamlabs/bento/v4/public/components/pusher"
	_ "github.com/warpstreamlabs/bento/v4/public/components/redis"
	_ "github.com/warpstreamlabs/bento/v4/public/components/sentry"
	_ "github.com/warpstreamlabs/bento/v4/public/components/sftp"
	_ "github.com/warpstreamlabs/bento/v4/public/components/snowflake"
	_ "github.com/warpstreamlabs/bento/v4/public/components/splunk"
	_ "github.com/warpstreamlabs/bento/v4/public/components/sql"
	_ "github.com/warpstreamlabs/bento/v4/public/components/statsd"
	_ "github.com/warpstreamlabs/bento/v4/public/components/twitter"
	_ "github.com/warpstreamlabs/bento/v4/public/components/wasm"
)
